type Activity {

    id: ID!

    attribute: Integer!
    name: String!
    description: String!
    popularity: String!
    preferences: [Preference] @relation

}

type Group {

    id: ID!

    chat: String!
    users: [User!] @relation

    createdAt: DateTime!
    lastUsed: DateTime!

}

type Relationship {

    id: ID!

    requester: User!
    addressee: User!
    status: Integer!

    createdAt: DateTime!
    updatedAt: DateTime!

}

type Event {

    id: ID!

    location: Location!
    author: User!
    chat: String!
    recurring: Boolean!
    participants: [User!] @relation

    createdAt: DateTime!
    startsAt: DateTime!
    endsAt: DateTime!

}

type Location {

    id: ID!

    name: String!
    geographicLocation: String!
    events: [Event!] @relation

}

type Preference {

    id: ID!

    profile: Profile!
    activity: Activity!
    experience: Integer!
    popularity: Integer!

}

type Profile {
    
    id: ID!
    
    user: User!
    fitnessLevel: Integer!
    gender: Integer!
    weight: Integer!
    description: String!
    phoneNumber: String!
    preferences: [Preference] @relation

    updatedAt: DateTime!

}

type User {

    id: ID!

    user: String!
    email: String!
    firstName: String!
    lastName: String!

    eventsCreated: [Event] @relation
    eventsJoined: [Event] @relation
    friendRequestsCreated: [Relationship] @relation
    friendRequestsRecieved: [Relationship] @relation
    groupsJoined: [Group] @relation
    profile: Profile!
    
    createdAt: DateTime!
    updatedAt: DateTime!

}