"""Initial migration.

Revision ID: 8b07af01a129
Revises: 
Create Date: 2022-08-03 02:11:40.968613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b07af01a129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('geo_location', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('locations_activities',
    sa.Column('location', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location', 'activity')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('fitness_level', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('activity', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('chat', sa.String(length=255), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['author'], ['profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat'),
    sa.UniqueConstraint('name')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('chat', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles_activities',
    sa.Column('profile', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile', 'activity')
    )
    op.create_table('profiles_events',
    sa.Column('profile', sa.Integer(), nullable=False),
    sa.Column('event', sa.Integer(), nullable=False),
    sa.Column('joined_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile', 'event')
    )
    op.create_table('profiles_groups',
    sa.Column('profile', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('num_texts', sa.Integer(), nullable=True),
    sa.Column('joined_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile', 'group')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles_groups')
    op.drop_table('profiles_events')
    op.drop_table('profiles_activities')
    op.drop_table('groups')
    op.drop_table('events')
    op.drop_table('relationships')
    op.drop_table('profiles')
    op.drop_table('locations_activities')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('activities')
    # ### end Alembic commands ###
