input createActivityInput {

    type: Integer!
    name: String!
    description: String

}

input updateActivityInput {
    
    id: ID!

    type: Integer
    name: String
    description: String

}

input deleteActivityInput {

    id: ID!

}