input createProfileInput {
    
    user: ID!

    fitnessLevel: Integer
    gender: Integer
    weight: Integer
    description: String
    phoneNumber: String
    
    preferences: [ID]

}

input updateProfileInput {
    
    id: ID!

    fitnessLevel: Integer
    gender: Integer
    weight: Integer
    description: String
    phoneNumber: String
    preferences: JSON

}