type Mutation {}

extend type Mutation {

    createUser(input: createUserInput!): UserCreationResult!

    updateUserInformation(input: updateUserInput!): UserModificationResult!
    updatePassword(input: updatePasswordInput!): UserModificationResult!

    deleteUser(input: deleteUserInput!): UserDeletionResult!

}

extend type Mutation {

    createProfile(createProfileInput!): ProfileCreationResult!

    updateProfile(updateProfileInput!): ProfileModificationResult!

}

extend type Mutation {

    createActivity(createActivityInput!): ActivityCreationResult!

    updateActivity(updateActivityInput!): ActivityModificationResult!

    deleteActivity(deleteActivityInput!): ActivityDeletionResult!

}

extend type Mutation {
    
}