type Mutation {}

extend type Mutation {

    createUser(input: createUserInput!): UserCreationResult!

    updateUserInformation(input: updateUserInput!): UserModificationResult!
    updatePassword(input: updatePasswordInput!): UserModificationResult!

    deleteUser(input: deleteUserInput!): UserDeletionResult!

}

extend type Mutation {

    createProfile(createProfileInput!): ProfileCreationResult!

    updateProfile(updateProfileInput!): ProfileModificationResult!

}

extend type Mutation {

    createActivity(createActivityInput!): ActivityCreationResult!

    updateActivity(updateActivityInput!): ActivityModificationResult!

    deleteActivity(deleteActivityInput!): ActivityDeletionResult!

}

extend type Mutation {
    
    createLocation(createLocationInput!): LocationCreationResult!
    
    updateLocation(updateLocationInput!): LocationModificationResult!

    deleteLocation(deleteLocationInput!): LocationDeletionResult!

}

extend type Mutation {

    createEvent(createEventInput!): EventCreationResult!

    updateEvent(updateEventInput!): EventModificationResult!

    deleteEvent(deleteEventInput!): EventDeletionResult!

}

extend type Mutation {

    createRelationship(createRelationshipInput!): RelationshipCreationResult!

    updateRelationship(updateRelationshipInput!): RelationshipModificationResult!

    deleteRelationship(deleteRelationshipInput!): RelationshipDeletionResult!

}

extend type Mutation {

    createGroup(createGroupInput!): GroupCreationResult!

    updateGroup(updateGroupInput!): GroupModificationResult!

    deleteGroup(deleteGroupInput!): GroupDeletionResult!

}