type Query {
    todos: TodosResult!
    todo(todoId: ID!): TodoResult
}

type Mutation {
    createTodo(description: String!, dueDate: String!): TodoResult!
    deleteTodo(todoId: ID!): deleteTodoResult!
    markDone(todoId: ID!): TodoResult!
    updateDueDate(todoId: ID!, newDate: String!): TodoResult!
}