type Activity {

    id: ID!

    attribute: Integer!
    name: String!
    description: String!
    preferences: [Preference!]

}

type Group {

    id: ID!

    chat: String!
    users: [User!] @relation

    lastUsed: DateTime!

}

type Relationship {

    id: ID!

    requester: User!
    addressee: User!
    status: Integer!

}

type Event {

    id: ID!

    location: Location
    author: User
    recurring: Boolean!
    participants: [User!] @relation

    createdAt: DateTime!
    startsAt: DateTime!
    endsAt: DateTime!

}

type Location {

    id: ID!

    name: String!
    geographicLocation: GeoLocation!
    events: [Event!] @relation

}

type Preference {

    id: ID!

    profile: Profile!
    activity: Activity!
    experience: Integer!

}

type Profile {
    
    id: ID!
    
    user: User!
    fitnessLevel: Integer!
    gender: Integer!
    weight: Integer!
    description: String!
    phoneNumber: String!
    preferences: [Preference!] @relation

    updatedAt: DateTime!

}

type User {

    id: ID!

    username: String!
    email: String!
    name: String!

    eventsCreated: [Event!]
    eventsJoined: [Event!]
    friendRequestsCreated: [Relationship!] @relation
    friendRequestsRecieved: [Relationship!] @relation
    groupsJoined: [Group!] @relation
    profile: Profile!
    
    createdAt: DateTime!
    updatedAt: DateTime!

}