type Activity {

    id: ID!

    attribute: Integer!
    name: String!
    description: String!
    preferences: [Preference!]
    locations: [Location]

}

type Group {

    id: ID!

    chat: ChatLog!
    users: [User!]

    lastUsed: DateTime!

}

type Relationship {

    id: ID!

    requester: User!
    recipient: User!
    status: Integer!

}

type Event {

    id: ID!

    name: String!
    description: String!
    chat: ChatLog!
    location: Location
    author: User
    recurring: Boolean!
    participants: [User!]

    startsAt: DateTime!
    endsAt: DateTime!

}

type Location {

    id: ID!

    name: String!
    geographicLocation: GeoLocation!
    events: [Event!]
    activities: [Activity]

}

type Preference {

    id: ID!

    profile: Profile!
    activity: Activity!
    experience: Integer

}

type Profile {
    
    id: ID!
    
    user: User!
    fitnessLevel: Integer!
    gender: Integer!
    weight: Integer!
    description: String!
    phoneNumber: String!
    eventsCreated: [Event!]
    eventsJoined: [Event!]
    friendRequestsCreated: [Relationship!] 
    friendRequestsRecieved: [Relationship!] 
    groupsJoined: [Group!]
    preferences: [Preference!]

}

type User {

    id: ID!

    username: String!
    email: String!
    name: String!
    profile: Profile!

    isStaff: Boolean!
    isSuperUser: Boolean!

}